import 'package:ninety/core/common/app_assets/app_assets.dart';
import 'package:ninety/core/models/name.dart';

class NamesProvider {
  static List<Name> names = [
    Name(
        id: 0,
        arabe: "الله",
        transliteration: "Allah",
        translation: "Allah ('Le Dieu' littéralement)",
        details:
            "Celui qui est la divinité, c’est-à-dire Celui qui mérite l’adoration, et à qui on doit l’extrême soumission et l’extrême humilité..",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: AudioAssets.allah,
        imagePath: ""),
    Name(
        id: 1,
        arabe: "ٱلْرَّحْمَـٰنُ",
        transliteration: "Ar-Rahmān",
        translation: "Le Tout-Miséricordieux",
        details:
            "Clément envers ses créatures. La clémence d'une mère envers son enfant est une partie infime de Son immense clémence envers Ses créatures. Son châtiment est le plus dur et sévère de tous les châtiments mais Sa clémence a précédé Sa colère ; et ce nom fait partie des noms que l’on n’attribue à nul autre qu'Allah.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 2,
        arabe: "ٱلْقُدُّوسُ",
        transliteration: "Al-Quddūs",
        translation: "Le Saint",
        details:
            "Celui qui est exempt de toute imperfection et de toute impureté. Il est pur et parfait dans Sa sainteté. ",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 3,
        arabe: "ٱلْمَلِكُ",
        transliteration: "Al-Malik",
        translation: "Le Souverain",
        details:
            "Celui qui possède le royaume parfait et complet. Il est le Roi absolu et incontesté de tout l'univers.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 4,
        arabe: "ٱلْقُدُّوسُ",
        transliteration: "Al-Quddūs",
        translation: "Le Saint",
        details:
            "Celui qui est exempt de toute imperfection et de toute impureté. Il est pur et parfait dans Sa sainteté. ",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 5,
        arabe: "ٱلْمَلِكُ",
        transliteration: "Al-Malik",
        translation: "Le Souverain",
        details:
            "Celui qui possède le royaume parfait et complet. Il est le Roi absolu et incontesté de tout l'univers.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 6,
        arabe: "ٱلْأَعْلَىٰ",
        transliteration: "Al-Aʿlā",
        translation: "Le Très-Haut",
        details:
            "Celui dont le rang est le plus élevé. Il est au-dessus de toute chose et de toute imperfection.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 7,
        arabe: "ٱلْكَبِيرُ",
        transliteration: "Al-Kabīr",
        translation: "Le Plus Grand",
        details:
            "Celui dont la grandeur et la magnificence sont incommensurables. Il est supérieur à toute création.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 8,
        arabe: "ٱلْحَفِيظُ",
        transliteration: "Al-Ḥafīẓ",
        translation: "Le Préservateur",
        details:
            "Celui qui protège et préserve tout. Rien n'échappe à Sa surveillance et à Sa préservation.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 9,
        arabe: "ٱلْمُقِيتُ",
        transliteration: "Al-Muqīt",
        translation: "Le Pourvoyeur",
        details:
            "Celui qui pourvoit à tous les besoins. Il nourrit et entretient toute la création.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 10,
        arabe: "ٱلْحَسِيبُ",
        transliteration: "Al-Ḥasīb",
        translation: "Le Comptable",
        details:
            "Celui qui tient un compte minutieux de toutes les actions et récompenses. Rien n'échappe à Sa comptabilité parfaite.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 11,
        arabe: "ٱلرَّقِيبُ",
        transliteration: "Ar-Raqīb",
        translation: "Le Vigilant",
        details:
            "Celui qui est attentif à tout ce qui se passe dans l'univers. Rien ne Lui échappe, et Il observe en permanence.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 12,
        arabe: "ٱلْمُجِيبُ",
        transliteration: "Al-Mujīb",
        translation: "L'Exauceur",
        details:
            "Celui qui répond à toutes les supplications et prières. Il accorde ce qui est le mieux pour Ses créatures.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 13,
        arabe: "ٱلْوَاسِعُ",
        transliteration: "Al-Wāsiʿ",
        translation: "L'Infiniment Vaste",
        details:
            "Celui dont la générosité, la miséricorde et la bonté sont illimitées. Son pardon et Ses bienfaits sont infinis.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 14,
        arabe: "ٱلْحَكِيمُ",
        transliteration: "Al-Ḥakīm",
        translation: "Le Sage",
        details:
            "Celui qui possède une sagesse parfaite et incontestée. Toutes Ses décisions et lois sont empreintes de sagesse.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 15,
        arabe: "ٱلْوَدُودُ",
        transliteration: "Al-Wadūd",
        translation: "L'Aimant",
        details:
            "Celui qui est plein d'amour et de bienveillance envers Ses créatures. Il aime Ses serviteurs et est aimé en retour.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 16,
        arabe: "ٱلْمَجِيدُ",
        transliteration: "Al-Majīd",
        translation: "Le Glorieux",
        details:
            "Celui qui est digne de toute gloire et de toute magnificence. Sa grandeur est incomparable.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 17,
        arabe: "ٱلْبَاعِثُ",
        transliteration: "Al-Bāʿith",
        translation: "Le Résurrecteur",
        details:
            "Celui qui ressuscite les morts au Jour de la Résurrection. Il est le Créateur et le Résurrecteur de toute vie.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 18,
        arabe: "ٱلشَّهِيدُ",
        transliteration: "Ash-Shahīd",
        translation: "Le Témoin",
        details:
            "Celui qui est témoin de tout ce qui se passe. Il est conscient de chaque action et rien ne Lui échappe.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 19,
        arabe: "ٱلْحَقُّ",
        transliteration: "Al-Ḥaqq",
        translation: "La Vérité",
        details:
            "Celui qui incarne la vérité absolue. Sa parole est véridique et Il est la réalité ultime de l'existence.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 20,
        arabe: "ٱلْوَكِيلُ",
        transliteration: "Al-Wakīl",
        translation: "Le Dépositaire de toute confiance",
        details:
            "Celui en qui on peut placer sa confiance en toute circonstance. Il est le gardien de toute chose.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 21,
        arabe: "ٱلْقَوِيُّ",
        transliteration: "Al-Qawwiyy",
        translation: "Le Fort",
        details:
            "Celui qui possède une force inébranlable. Il est capable de tout et rien ne Lui est impossible.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 22,
        arabe: "ٱلْمَتِينُ",
        transliteration: "Al-Matīn",
        translation: "Le Solide",
        details:
            "Celui qui est ferme, stable et inébranlable. Son pouvoir et Sa solidité sont incontestés.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 23,
        arabe: "ٱلْوَلِيُّ",
        transliteration: "Al-Walī",
        translation: "Le Protecteur",
        details:
            "Celui qui protège et prend soin de Ses serviteurs croyants. Il est le meilleur gardien et protecteur.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 24,
        arabe: "ٱلْحَمِيدُ",
        transliteration: "Al-Ḥamīd",
        translation: "Le Loué",
        details:
            "Celui qui mérite la louange parfaite et inconditionnelle. Il est digne de toute reconnaissance.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 25,
        arabe: "ٱلْمُحْصِيُ",
        transliteration: "Al-Muḥṣī",
        translation: "Le Comptable",
        details:
            "Celui qui tient compte de toutes choses. Rien n'échappe à Sa comptabilité précise.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 26,
        arabe: "ٱلْمُبْدِئُ",
        transliteration: "Al-Mubdīʾ",
        translation: "Celui qui Initie",
        details:
            "Celui qui commence la création. Il est l'origine de toute existence et de toute innovation.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 27,
        arabe: "ٱلْمُعِيدُ",
        transliteration: "Al-Muʿīd",
        translation: "Le Répétiteur",
        details:
            "Celui qui ramène la création après qu'elle a disparu. Il fera revivre les morts au Jour de la Résurrection.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 28,
        arabe: "ٱلْمُحْيِي",
        transliteration: "Al-Muḥyī",
        translation: "Celui qui Donne la Vie",
        details:
            "Celui qui donne la vie à la création. Il est la source de toute vie et de toute vitalité.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 29,
        arabe: "ٱلْمُمِيتُ",
        transliteration: "Al-Mumīt",
        translation: "Celui qui Donne la Mort",
        details:
            "Celui qui prend la vie de toute chose. Toute existence est soumise à Sa volonté.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 30,
        arabe: "ٱلْحَيُّ",
        transliteration: "Al-Ḥayy",
        translation: "Le Vivant",
        details:
            "Celui qui est éternellement vivant. Sa vie est absolue et éternelle, et Il est source de vie pour tout.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 31,
        arabe: "ٱلْقَيُّومُ",
        transliteration: "Al-Qayyūm",
        translation: "Celui qui Subsiste par lui-même",
        details:
            "Celui qui est éternellement auto-subsistant. Il est indépendant et maintient toute la création.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 32,
        arabe: "ٱلْوَاجِدُ",
        transliteration: "Al-Wājid",
        translation: "Le Présent",
        details:
            "Celui qui est toujours présent et dont la connaissance englobe toute chose.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 33,
        arabe: "ٱلْمَاجِدُ",
        transliteration: "Al-Mājid",
        translation: "Le Noble",
        details:
            "Celui qui est digne de toute noblesse. Sa grandeur et Sa magnificence sont infinies.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 34,
        arabe: "ٱلْوَاحِدُ",
        transliteration: "Al-Wāḥid",
        translation: "L'Unique",
        details:
            "Celui qui est unique dans Sa divinité et dans Ses attributs. Il n'y a rien de comparable à Lui.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 35,
        arabe: "ٱلْأَحَدُ",
        transliteration: "Al-Aḥad",
        translation: "L'Indivisible",
        details:
            "Celui qui est unique et indivisible. Il n'a pas d'associé ni de semblable.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 36,
        arabe: "ٱلصَّمَدُ",
        transliteration: "Aṣ-Ṣamad",
        translation: "Le Seul à qui on fait appel",
        details:
            "Celui qui est invoqué pour chaque besoin. Toute la création dépend de Lui.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 37,
        arabe: "ٱلْقَادِرُ",
        transliteration: "Al-Qādir",
        translation: "Le Tout-Puissant",
        details:
            "Celui qui a un pouvoir absolu. Rien ne peut résister à Sa volonté.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 38,
        arabe: "ٱلْمُقْتَدِرُ",
        transliteration: "Al-Muqtadir",
        translation: "Le Puissant",
        details:
            "Celui qui détermine le destin de toute chose. Il est capable de réaliser tout ce qu'Il veut.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 39,
        arabe: "ٱلْمُقِيتُ",
        transliteration: "Al-Muqīt",
        translation: "Le Pourvoyeur",
        details:
            "Celui qui pourvoit à tous les besoins. Il nourrit et entretient toute la création.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 40,
        arabe: "ٱلْوَكِيلُ",
        transliteration: "Al-Wakīl",
        translation: "Le Dépositaire de toute confiance",
        details:
            "Celui en qui on peut placer sa confiance en toute circonstance. Il est le gardien de toute chose.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 41,
        arabe: "ٱلْمُجِيبُ",
        transliteration: "Al-Mujīb",
        translation: "L'Exauceur",
        details:
            "Celui qui répond à toutes les supplications et prières. Il accorde ce qui est le mieux pour Ses créatures.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 42,
        arabe: "ٱلْوَاسِعُ",
        transliteration: "Al-Wāsiʿ",
        translation: "L'Infiniment Vaste",
        details:
            "Celui dont la générosité, la miséricorde et la bonté sont illimitées. Son pardon et Ses bienfaits sont infinis.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 43,
        arabe: "ٱلْحَكِيمُ",
        transliteration: "Al-Ḥakīm",
        translation: "Le Sage",
        details:
            "Celui qui possède une sagesse parfaite et incontestée. Toutes Ses décisions et lois sont empreintes de sagesse.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 44,
        arabe: "ٱلْوَدُودُ",
        transliteration: "Al-Wadūd",
        translation: "L'Aimant",
        details:
            "Celui qui est plein d'amour et de bienveillance envers Ses créatures. Il aime Ses serviteurs et est aimé en retour.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 45,
        arabe: "ٱلْمَجِيدُ",
        transliteration: "Al-Majīd",
        translation: "Le Glorieux",
        details:
            "Celui qui est digne de toute gloire et de toute magnificence. Sa grandeur est incomparable.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 46,
        arabe: "ٱلْبَاعِثُ",
        transliteration: "Al-Bāʿith",
        translation: "Le Résurrecteur",
        details:
            "Celui qui ressuscite les morts au Jour de la Résurrection. Il est le Créateur et le Résurrecteur de toute vie.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 47,
        arabe: "ٱلشَّهِيدُ",
        transliteration: "Ash-Shahīd",
        translation: "Le Témoin",
        details:
            "Celui qui est témoin de tout ce qui se passe. Il est conscient de chaque action et rien ne Lui échappe.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 48,
        arabe: "ٱلْحَقُّ",
        transliteration: "Al-Ḥaqq",
        translation: "La Vérité",
        details:
            "Celui qui incarne la vérité absolue. Sa parole est véridique et Il est la réalité ultime de l'existence.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 49,
        arabe: "ٱلْوَكِيلُ",
        transliteration: "Al-Wakīl",
        translation: "Le Dépositaire de toute confiance",
        details:
            "Celui en qui on peut placer sa confiance en toute circonstance. Il est le gardien de toute chose.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 50,
        arabe: "ٱلْقَوِيُّ",
        transliteration: "Al-Qawwiyy",
        translation: "Le Fort",
        details:
            "Celui qui possède une force inébranlable. Il est capable de tout et rien ne Lui est impossible.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 51,
        arabe: "ٱلْمَتِينُ",
        transliteration: "Al-Matīn",
        translation: "Le Solide",
        details:
            "Celui qui est ferme, stable et inébranlable. Son pouvoir et Sa solidité sont incontestés.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 52,
        arabe: "ٱلْوَلِيُّ",
        transliteration: "Al-Walī",
        translation: "Le Protecteur",
        details:
            "Celui qui protège et prend soin de Ses serviteurs croyants. Il est le meilleur gardien et protecteur.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 53,
        arabe: "ٱلْحَمِيدُ",
        transliteration: "Al-Ḥamīd",
        translation: "Le Loué",
        details:
            "Celui qui mérite la louange parfaite et inconditionnelle. Il est digne de toute reconnaissance.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 54,
        arabe: "ٱلْمُحْصِيُ",
        transliteration: "Al-Muḥṣī",
        translation: "Le Comptable",
        details:
            "Celui qui tient compte de toutes choses. Rien n'échappe à Sa comptabilité précise.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 55,
        arabe: "ٱلْمُبْدِئُ",
        transliteration: "Al-Mubdīʾ",
        translation: "Celui qui Initie",
        details:
            "Celui qui commence la création. Il est l'origine de toute existence et de toute innovation.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 56,
        arabe: "ٱلْمُعِيدُ",
        transliteration: "Al-Muʿīd",
        translation: "Le Répétiteur",
        details:
            "Celui qui ramène la création après qu'elle a disparu. Il fera revivre les morts au Jour de la Résurrection.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 57,
        arabe: "ٱلْمُحْيِي",
        transliteration: "Al-Muḥyī",
        translation: "Celui qui Donne la Vie",
        details:
            "Celui qui donne la vie à la création. Il est la source de toute vie et de toute vitalité.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 58,
        arabe: "ٱلْمُمِيتُ",
        transliteration: "Al-Mumīt",
        translation: "Celui qui Donne la Mort",
        details:
            "Celui qui prend la vie de toute chose. Toute existence est soumise à Sa volonté.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 59,
        arabe: "ٱلْحَيُّ",
        transliteration: "Al-Ḥayy",
        translation: "Le Vivant",
        details:
            "Celui qui est éternellement vivant. Sa vie est absolue et éternelle, et Il est source de vie pour tout.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 60,
        arabe: "ٱلْقَيُّومُ",
        transliteration: "Al-Qayyūm",
        translation: "Celui qui Subsiste par lui-même",
        details:
            "Celui qui est éternellement auto-subsistant. Il est indépendant et maintient toute la création.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 61,
        arabe: "ٱلْمَجِيبُ",
        transliteration: "Al-Mujīb",
        translation: "L'Exauceur",
        details:
            "Celui qui répond à toutes les supplications et prières. Il accorde ce qui est le mieux pour Ses créatures.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 62,
        arabe: "ٱلْوَاسِعُ",
        transliteration: "Al-Wāsiʿ",
        translation: "L'Infiniment Vaste",
        details:
            "Celui dont la générosité, la miséricorde et la bonté sont illimitées. Son pardon et Ses bienfaits sont infinis.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 63,
        arabe: "ٱلْحَكِيمُ",
        transliteration: "Al-Ḥakīm",
        translation: "Le Sage",
        details:
            "Celui qui possède une sagesse parfaite et incontestée. Toutes Ses décisions et lois sont empreintes de sagesse.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 64,
        arabe: "ٱلْوَدُودُ",
        transliteration: "Al-Wadūd",
        translation: "L'Aimant",
        details:
            "Celui qui est plein d'amour et de bienveillance envers Ses créatures. Il aime Ses serviteurs et est aimé en retour.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 65,
        arabe: "ٱلْمَجِيدُ",
        transliteration: "Al-Majīd",
        translation: "Le Glorieux",
        details:
            "Celui qui est digne de toute gloire et de toute magnificence. Sa grandeur est incomparable.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 66,
        arabe: "ٱلْبَاعِثُ",
        transliteration: "Al-Bāʿith",
        translation: "Le Résurrecteur",
        details:
            "Celui qui ressuscite les morts au Jour de la Résurrection. Il est le Créateur et le Résurrecteur de toute vie.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 67,
        arabe: "ٱلشَّهِيدُ",
        transliteration: "Ash-Shahīd",
        translation: "Le Témoin",
        details:
            "Celui qui est témoin de tout ce qui se passe. Il est conscient de chaque action et rien ne Lui échappe.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 68,
        arabe: "ٱلْحَقُّ",
        transliteration: "Al-Ḥaqq",
        translation: "La Vérité",
        details:
            "Celui qui incarne la vérité absolue. Sa parole est véridique et Il est la réalité ultime de l'existence.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 69,
        arabe: "ٱلْوَكِيلُ",
        transliteration: "Al-Wakīl",
        translation: "Le Dépositaire de toute confiance",
        details:
            "Celui en qui on peut placer sa confiance en toute circonstance. Il est le gardien de toute chose.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 70,
        arabe: "ٱلْقَوِيُّ",
        transliteration: "Al-Qawwiyy",
        translation: "Le Fort",
        details:
            "Celui qui possède une force inébranlable. Il est capable de tout et rien ne Lui est impossible.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 71,
        arabe: "ٱلْمَتِينُ",
        transliteration: "Al-Matīn",
        translation: "Le Solide",
        details:
            "Celui qui est ferme, stable et inébranlable. Son pouvoir et Sa solidité sont incontestés.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 72,
        arabe: "ٱلْوَلِيُّ",
        transliteration: "Al-Walī",
        translation: "Le Protecteur",
        details:
            "Celui qui protège et prend soin de Ses serviteurs croyants. Il est le meilleur gardien et protecteur.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 73,
        arabe: "ٱلْحَمِيدُ",
        transliteration: "Al-Ḥamīd",
        translation: "Le Loué",
        details:
            "Celui qui mérite la louange parfaite et inconditionnelle. Il est digne de toute reconnaissance.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 74,
        arabe: "ٱلْمُحْصِيُ",
        transliteration: "Al-Muḥṣī",
        translation: "Le Comptable",
        details:
            "Celui qui tient compte de toutes choses. Rien n'échappe à Sa comptabilité précise.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 75,
        arabe: "ٱلْمُبْدِئُ",
        transliteration: "Al-Mubdīʾ",
        translation: "Celui qui Initie",
        details:
            "Celui qui commence la création. Il est l'origine de toute existence et de toute innovation.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 76,
        arabe: "ٱلْمُعِيدُ",
        transliteration: "Al-Muʿīd",
        translation: "Le Répétiteur",
        details:
            "Celui qui ramène la création après qu'elle a disparu. Il fera revivre les morts au Jour de la Résurrection.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 77,
        arabe: "ٱلْمُحْيِي",
        transliteration: "Al-Muḥyī",
        translation: "Celui qui Donne la Vie",
        details:
            "Celui qui donne la vie à la création. Il est la source de toute vie et de toute vitalité.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 78,
        arabe: "ٱلْمُمِيتُ",
        transliteration: "Al-Mumīt",
        translation: "Celui qui Donne la Mort",
        details:
            "Celui qui prend la vie de toute chose. Toute existence est soumise à Sa volonté.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 79,
        arabe: "ٱلْحَيُّ",
        transliteration: "Al-Ḥayy",
        translation: "Le Vivant",
        details:
            "Celui qui est éternellement vivant. Sa vie est absolue et éternelle, et Il est source de vie pour tout.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 80,
        arabe: "ٱلْقَيُّومُ",
        transliteration: "Al-Qayyūm",
        translation: "Celui qui Subsiste par lui-même",
        details:
            "Celui qui est éternellement auto-subsistant. Il est indépendant et maintient toute la création.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 81,
        arabe: "ٱلْمُتَكَبِّرُ",
        transliteration: "Al-Mutaqabbir",
        translation: "Le Suprême",
        details:
            "Celui qui est supérieur en grandeur et en majesté. Il est le plus grand de tous, au-dessus de toute imperfection.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 82,
        arabe: "ٱلْخَالِقُ",
        transliteration: "Al-Khāliq",
        translation: "Le Créateur",
        details:
            "Celui qui crée tout à partir de rien. Il est l'origine de toute existence.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 83,
        arabe: "ٱلْبَارِئُ",
        transliteration: "Al-Bāriʾ",
        translation: "Le Novateur",
        details:
            "Celui qui conçoit et façonne toute chose en perfection. Il est le Créateur qui donne forme à la création.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 84,
        arabe: "ٱلْمُصَوِّرُ",
        transliteration: "Al-Muṣawwir",
        translation: "Le Formateur",
        details:
            "Celui qui façonne et forme toute chose de manière parfaite. Il est l'Artisan de toute beauté.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 85,
        arabe: "ٱلْغَفَّارُ",
        transliteration: "Al-Ghaffār",
        translation: "L'Infiniment Pardonneur",
        details:
            "Celui qui pardonne de manière répétée et infinie. Sa miséricorde englobe tous les péchés.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 86,
        arabe: "ٱلْقَهَّارُ",
        transliteration: "Al-Qahhār",
        translation: "Le Dominateur Suprême",
        details:
            "Celui qui a un pouvoir absolu et exerce une domination incontestée sur toute la création.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 87,
        arabe: "ٱلْوَهَّابُ",
        transliteration: "Al-Wahhāb",
        translation: "Le Donateur Suprême",
        details:
            "Celui qui donne de manière généreuse et abondante. Il est le donateur ultime de tout bienfait.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 88,
        arabe: "ٱلْرَّزَّاقُ",
        transliteration: "Ar-Razzāq",
        translation: "Le Pourvoyeur",
        details:
            "Celui qui pourvoit à tous les besoins de Ses créatures. Il est le dispensateur de toute subsistance.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 89,
        arabe: "ٱلْفَتَّاحُ",
        transliteration: "Al-Fattāḥ",
        translation: "Le Dévoileur",
        details:
            "Celui qui ouvre les portes de la réussite et de la compréhension. Il révèle la vérité et apporte la clarté.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 90,
        arabe: "ٱلْعَلِيمُ",
        transliteration: "Al-ʿAlīm",
        translation: "L'Omniscient",
        details:
            "Celui qui connaît toutes choses, passées, présentes et futures. Sa connaissance est infinie et absolue.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 91,
        arabe: "ٱلْقَابِضُ",
        transliteration: "Al-Qābiḍ",
        translation: "Le Resserreur",
        details:
            "Celui qui retient et restreint. Il contrôle toute chose selon Sa sagesse et Sa volonté.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 92,
        arabe: "ٱلْبَاسِطُ",
        transliteration: "Al-Bāsiṭ",
        translation: "Le Dispensateur de l'abondance",
        details:
            "Celui qui étend Sa miséricorde, Ses bienfaits et Sa générosité. Il est le pourvoyeur d'abondance.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 93,
        arabe: "ٱلْخَافِضُ",
        transliteration: "Al-Khāfiḍ",
        translation: "Celui qui Avilit",
        details:
            "Celui qui humilie les orgueilleux et les injustes. Rien n'est élevé au-dessus de Sa volonté.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 94,
        arabe: "ٱلْرَّافِعُ",
        transliteration: "Ar-Rāfiʿ",
        translation: "Celui qui Élève",
        details:
            "Celui qui élève en rang et en honneur. Il est le source de toute élévation et de toute dignité.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 95,
        arabe: "ٱلْمُعِزُّ",
        transliteration: "Al-Muʿizz",
        translation: "Celui qui Donne la Puissance",
        details:
            "Celui qui accorde la force, la puissance et la dignité. Il est le protecteur et le défenseur de Ses serviteurs.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 96,
        arabe: "ٱلْمُذِلُّ",
        transliteration: "Al-Muḍill",
        translation: "Celui qui Avilit",
        details:
            "Celui qui humilie les arrogants et les injustes. Le pouvoir et l'honneur sont soumis à Sa souveraineté.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 97,
        arabe: "ٱلْسَّمِيعُ",
        transliteration: "As-Samīʿ",
        translation: "L'Audient",
        details:
            "Celui qui entend tout, même les chuchotements. Rien n'échappe à Sa connaissance auditive.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 98,
        arabe: "ٱلْبَصِيرُ",
        transliteration: "Al-Baṣīr",
        translation: "Le Voyant",
        details:
            "Celui qui voit tout, même ce qui est caché. Sa connaissance est infinie et absolue.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
    Name(
        id: 99,
        arabe: "ٱلْحَكَمُ",
        transliteration: "Al-Ḥakam",
        translation: "Le Juge Suprême",
        details:
            "Celui qui juge de manière parfaite et juste. Il est la source de toute justice et de toute sagesse.",
        sampleDoua: [],
        benefite: "",
        reference: "",
        audioPath: "",
        imagePath: ""),
  ];
}
